# UID=${UID} GID=${GID} docker compose -f compose.yaml up -d

services:
    eduart-node-red-astro:
        build:
            context: ..
            dockerfile: docker/node-red.Dockerfile
        network_mode: host
        command: node-red --userDir /data
        restart: always
        privileged: true
        ipc: host
        pid: host
        volumes:
            - node_red_user_data:/data:rw
            - /dev/shm:/dev/shm:rw

volumes:
    node_red_user_data:
